### ISSUE TITLE
Style the paypal window

### ISSUE THREAD

**Issue by morbidick** [morbidick/paypal-express-checkout#2]
Maybe pass a slot over the postMessage bridge?

**Comment by chwzr** [comment]
Why not using a iframe (for the original pp express button) instead a whole new window (to reduce the amount of clicks needed but render the button inside light dom. Communication to/from the iframe can be done with events.  [This ](https://github.com/vpusher/x-frame) element shows how to do this.). 
Its not clean, but better than let the users click twice, bc more clicks -> lower sales rate...

**Comment by morbidick** [comment]
The paypal script has two issues forcing this work around, [it doesnt work inside an iframe](https://github.com/paypal/paypal-checkout/issues/125) and [a click cant be triggered via js](https://github.com/paypal/paypal-checkout/issues/287).

The first issue seems to be resolved, I'm currently using `<paypal-button-form>` but might have another look the next few days.
